### ISSUE TITLE
could you please upload the "65%_ages.txt" file, thanks.

### ISSUE THREAD

**Issue by liamxg** [LeoFeatherstone/helicoBycatch#1]
@LeoFeatherstone

**Comment by LeoFeatherstone** [comment]
Hi  @liamxg,

I've added the file you are after in `/data/65%25_ages.txt `. 

I have also neatened the code and restructured the repo. I hope this makes it easier to work with.

Thanks,
Leo

**Comment by liamxg** [comment]
@LeoFeatherstone thanks, that's great.

**Comment by liamxg** [comment]
could you please upload the "./data/COI_653_f.treefile" file please, thanks.

**Comment by LeoFeatherstone** [comment]
Hi again @liamxg,

The tree is now included at `data/COI_653bp_f.treefile`. NB, all phylograms can be reproduced using the `data/ml_trees.sh` script too.

All the best,
Leo

**Comment by LeoFeatherstone** [comment]
Hi @liamxg ,

Apologies, I pushed an older version of the COI tree previously. It's now updated.

Cheers,
Leo

**Comment by liamxg** [comment]
@LeoFeatherstone thanks.
