### ISSUE TITLE
the output is FALSE, is the normal?

### ISSUE THREAD

**Issue by liamxg** [LeoFeatherstone/helicoBycatch#2]
<img width="690" alt="image" src="https://user-images.githubusercontent.com/46078579/230870956-c853b81a-99a3-467f-8b83-f9344aefdadd.png">

**Comment by liamxg** [comment]
@LeoFeatherstone

**Comment by LeoFeatherstone** [comment]
Hi again @liamxg ,

Thanks for pointing this out. I believe the line of code captured here is from the `format_tips.R` file which was used to get a consistent format for tip labels for the 65% data.

It was intended as a one-off to fix the tip labels, but if run more than once results in over labeling the local of tips. Eg. `AUS_tip` -> `AUS_AUS_tip` if run twice. To protect against this I've made sure tip labels are correct in the 65% coverage alignments and removed  `format_tips.R`. You shouldn't need to run it to replicate the rest of the analysis.

Thanks again for your consideration here,

Leo

**Comment by liamxg** [comment]
@LeoFeatherstone thanks for your kindly reply.
