### ISSUE TITLE
is this duplicates or not?

### ISSUE THREAD

**Issue by liamxg** [LeoFeatherstone/helicoBycatch#3]
aln <- lapply(aln_files, function(x) read.dna(x, format = "fasta"))
aln <- lapply(aln_files, function(x) read.FASTA(x, type = "DNA"))

**Comment by liamxg** [comment]
@LeoFeatherstone

**Comment by LeoFeatherstone** [comment]
Hi @liamxg ,

Can you point me to the file you are viewing this in. I wonder if it's still there if you pull the most recent version of the repo.

Cheers,
Leo

**Comment by liamxg** [comment]
@LeoFeatherstone，it is in the previous version of label_format.R file. :)

**Comment by LeoFeatherstone** [comment]
Hi again @liamxg,

No worries :). Just to be clear, that file is no longer needed to reproduce the analyses in the most recent repo. Please let me know if you need anything further for this.

Cheers,
Leo
