### ISSUE TITLE
Could you explain this: "Max Clusters = 10 to cover 6" in the "DAPC_figs.R"file?

### ISSUE THREAD

**Issue by liamxg** [LeoFeatherstone/helicoBycatch#4]
@LeoFeatherstone

**Comment by LeoFeatherstone** [comment]
Hi @liamxg,

That comment is an artifact from earlier code that found its way through my recent refactoring. In the latest update of `DAPC_figs.R` we just set `n.clust=2` in accordance with the manuscript, so one does not need to worry about the `max.clust` argument anymore. It was superfluously setting a search for up to 10 clusters, when we fix the numbers of clusters to 2 (matching the subspecies hypothesis) apriori. Thanks for being thorough and pointing this out.

Cheers,
Leo

**Comment by liamxg** [comment]
@LeoFeatherstone thanks.

**Comment by liamxg** [comment]
@LeoFeatherstone could I know if your manuscript is available?

**Comment by LeoFeatherstone** [comment]
No worries :) - it's in review currently, but I will update the repo once it is out.

**Comment by liamxg** [comment]
@LeoFeatherstone can not wait it published.
