### ISSUE TITLE
is this normal?

### ISSUE THREAD

**Issue by liamxg** [LeoFeatherstone/helicoBycatch#5]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/46078579/231690775-dfb3d907-c14d-451d-9238-24078a65c653.png">

**Comment by liamxg** [comment]
@LeoFeatherstone

**Comment by LeoFeatherstone** [comment]
Hi @liamxg ,

That is normal unfortunately - they are just warnings about the plotting window. There is a small bug in the COI plot that I will address in an update shortly.

**Comment by liamxg** [comment]
@LeoFeatherstone thanks, you are so nice person. :-)
