### ISSUE TITLE
The issue of "coi_clustered" in the "DAPC_figs.R" file

### ISSUE THREAD

**Issue by liamxg** [LeoFeatherstone/helicoBycatch#6]
The "coi_clustered <- find.clusters(coi_genind, max.n.clust = 100, n.pca = 100)" should be"
"coi_clustered <- find.clusters(coi_genind, max.n.clust = 10, n.pca = 73) ?

**Comment by liamxg** [comment]
@LeoFeatherstone

**Comment by LeoFeatherstone** [comment]
Hi @liamxg,

Thanks for spotting this. It has been updated in the most recent update of `DAPC_figs.R` that produces the same output as in the manuscript, but with more sensible commands in `adegenet`. Regarding the line here, a `n.clust=2` argument has been added to sidestep searching for 10 clusters which is excessive. `n.pca` is also 13 now, the correct value.

Many thanks,
Leo

**Comment by liamxg** [comment]
@LeoFeatherstone great.
