### ISSUE TITLE
could I know why you set "nf = 3", and "n.da = 10"? thanks.

### ISSUE THREAD

**Issue by liamxg** [LeoFeatherstone/helicoBycatch#8]
@LeoFeatherstone

**Comment by LeoFeatherstone** [comment]
Hi @liamxg,

`nf=3` simply tells the function how many of the PCs to store as data points after running the function. I only needed 2, but chose 3 just to see what was beyond. This won't affect the results. `n.da` similarly stores the number of axes preserved from dapc.

Cheers,
Leo

**Comment by liamxg** [comment]
@LeoFeatherstone thanks again for your reply. :)
